### ISSUE TITLE
Unable to run v1.2.1.1, I am getting NoClassSettingsException

### ISSUE THREAD

**Issue by evoxmusic** [octaldata/streamops#17]
Hi @sksamuel,

It seems that something is missing from your version 1.2.1.1..

```
failed to create river [neo4j][my_neo_river]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [neo4j]
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
        at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
        at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
        at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: neo4j
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
        ... 9 more
```

Do you have a fix for this ?

**Comment by remix88** [comment]
I got the same error, and I think the installation instructions are missing one step:

> Download "elasticsearch-river-neo4j-1.2.1.1.jar" from [Click here](http://central.maven.org/maven2/com/sksamuel/elasticsearch/elasticsearch-river-neo4j/1.2.1.1/elasticsearch-river-neo4j-1.2.1.1.jar) and copy it to "HOME_DIRECTORY_OF_ES/lib" folder.

This solved it for me.

Found at http://stackoverflow.com/questions/28323323/examples-about-integration-of-elasticsearch-with-neo4j
