### ISSUE TITLE
Trouble creating river with neo4j 2.1.2 and ES 1.2.1

### ISSUE THREAD

**Issue by tzintzuni** [octaldata/streamops#19]
Hi, I've got Neo4j v 2.1.2 and elastic search v 1.2.1 running on ubuntu but I'm having trouble with the plugin. It seems to have installed just fine, but it doesn't seem to get the river set up properly. Here's the command I run to start it:

curl -XPUT 'http://localhost:9200/_river/bcr_river/_meta' -d '{
    "type": "neo4j",
    "neo4j": {
        "uri": "http://localhost:7474/db/data",
        "interval": 3600000
    },
    "index": {
        "name": "bcr",
        "type": "nodes"
    }
}'

I get this response:

{
   "_index": "_river",
   "_type": "bcr_river",
   "_id": "_meta",
   "_version": 1,
   "created": true
}

But this shows up in the log:

[2014-08-01 11:02:49,840][INFO ][cluster.metadata         ] [Bengal] [_river] update_mapping [bcr_river](dynamic)
[2014-08-01 11:02:49,844][WARN ][river                    ] [Bengal] failed to create river [neo4j][bcr_river]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [neo4j]
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
        at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
        at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
        at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: neo4j
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
        ... 9 more
[2014-08-01 11:02:49,904][INFO ][cluster.metadata         ] [Bengal] [_river] update_mapping [bcr_river](dynamic)

And I get a similar error when trying to check the status. Could it be the version of Neo4j is too new?

**Comment by SlimBN** [comment]
up :+1: :/

**Comment by SlimBN** [comment]
Have you found a solution to that problem please :/

**Comment by swainjo** [comment]
up :+1:

**Comment by remix88** [comment]
I got the same error, and I think the installation instructions are missing one step:

> Download "elasticsearch-river-neo4j-1.2.1.1.jar" from [Click here](http://central.maven.org/maven2/com/sksamuel/elasticsearch/elasticsearch-river-neo4j/1.2.1.1/elasticsearch-river-neo4j-1.2.1.1.jar) and copy it to "HOME_DIRECTORY_OF_ES/lib" folder.

This solved it for me.

Found at http://stackoverflow.com/questions/28323323/examples-about-integration-of-elasticsearch-with-neo4j
